#!/bin/bash
# DesignShip — OpenCode/Claude Runner (via ralphex)
# Usage: ./run-opencode.sh [start|ship|mvp|status|dashboard|config]
# Environment: DESIGNSHIP_AI=opencode|claude (default: opencode)

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# AI provider selection (opencode or claude)
DESIGNSHIP_AI="${DESIGNSHIP_AI:-opencode}"

PORT=8181
SESSION_TIMEOUT=45m
IDLE_TIMEOUT=15m

# Setup ralphex configuration based on selected AI provider
setup_config() {
    local provider="$1"
    local config_file=".ralphex/config"
    
    # Backup original config if not already backed up
    if [ ! -f ".ralphex/config.backup" ]; then
        cp "$config_file" ".ralphex/config.backup"
        echo "  [config] Backed up original config to .ralphex/config.backup"
    fi
    
    # Remove any previous auto-generated AI provider config
    if grep -q "# --- OpenCode/Claude Configuration" "$config_file" 2>/dev/null; then
        # Remove everything from the marker to the end
        sed -i '/# --- OpenCode\/Claude Configuration/,$d' "$config_file" 2>/dev/null || \
            sed -i.bak '/# --- OpenCode\/Claude Configuration/,$d' "$config_file" && rm -f "$config_file.bak"
    fi
    
    case "$provider" in
        opencode)
            echo "  [config] Configuring ralphex for OpenCode..."
            cat >> "$config_file" << 'EOF'

# --- OpenCode/Claude Configuration (auto-generated by run-opencode.sh) ---
# Provider: opencode
claude_command = opencode
claude_args = run --format json --continue
claude_error_patterns = rate limit,API Error:,quota exceeded,context window exceeded,token limit,connection error
claude_limit_patterns = rate limit,quota exceeded,RateLimitError,usage limit,rateLimit
EOF
            ;;
        claude)
            echo "  [config] Configuring ralphex for Claude..."
            cat >> "$config_file" << 'EOF'

# --- OpenCode/Claude Configuration (auto-generated by run-opencode.sh) ---
# Provider: claude
claude_command = claude
claude_args = --dangerously-skip-permissions --output-format stream-json --verbose
claude_error_patterns = You've hit your limit,API Error:,cannot be launched inside another Claude Code session
claude_limit_patterns = You've hit your limit
EOF
            ;;
        *)
            echo "  ERROR: Unknown AI provider: $provider"
            echo "  Use: DESIGNSHIP_AI=opencode or DESIGNSHIP_AI=claude"
            exit 1
            ;;
    esac
    
    echo "  [config] Configuration updated for $provider"
}

run_plan() {
    local label="$1"
    local plan="$2"

    if [ ! -f "$plan" ]; then
        echo ""
        echo "  ERROR: plan file not found: $plan"
        echo "  Available plans:"
        ls docs/plans/*.md 2>/dev/null | sed 's|^|    |' || echo "    (none found)"
        exit 1
    fi

    local branch
    branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

    echo ""
    echo "  DesignShip — $label"
    echo "  $(printf '%.0s=' $(seq 1 $((${#label} + 14))))"
    echo "  Provider:  $DESIGNSHIP_AI"
    echo "  Plan:      $plan"
    echo "  Branch:    $branch"
    echo "  Dashboard: http://localhost:$PORT"
    echo ""
    echo "  Ctrl+\ to pause and steer"
    echo "  Ctrl+C to abort"
    echo ""

    setup_config "$DESIGNSHIP_AI"

    exec ralphex --serve --port "$PORT" \
        --session-timeout "$SESSION_TIMEOUT" \
        --idle-timeout "$IDLE_TIMEOUT" \
        "$plan"
}

case "${1:-}" in

start|ship)
    # Default entry point. Runs the ship plan (README + GitHub + Vercel deploy).
    run_plan "Document, Push, Deploy" "docs/plans/designship-ship.md"
    ;;

mvp)
    run_plan "MVP Build" "docs/plans/designship-mvp.md"
    ;;

status)
    echo ""
    echo "  Plan Status (Provider: $DESIGNSHIP_AI)"
    echo "  ==========="
    echo ""
    for plan in docs/plans/*.md docs/plans/completed/*.md; do
        [ -f "$plan" ] || continue
        name=$(head -1 "$plan" | sed 's/# Plan: //')
        set +e
        done=$(grep -c "^\- \[x\]" "$plan" 2>/dev/null)
        todo=$(grep -c "^\- \[ \]" "$plan" 2>/dev/null)
        set -e
        done=${done:-0}
        todo=${todo:-0}
        total=$((done + todo))
        if [ "$total" -gt 0 ]; then
            pct=$((done * 100 / total))
        else
            pct=0
        fi
        rel="${plan#docs/plans/}"
        printf "  %-32s %s\n" "$rel:" "$name"
        printf "  %-32s %d/%d tasks (%d%%)\n" "" "$done" "$total" "$pct"
        echo ""
    done
    ;;

dashboard)
    echo "Starting dashboard only on port $PORT (Provider: $DESIGNSHIP_AI)..."
    setup_config "$DESIGNSHIP_AI"
    exec ralphex --serve --port "$PORT" --watch "$REPO_ROOT"
    ;;

config|setup)
    setup_config "$DESIGNSHIP_AI"
    echo ""
    echo "  Configuration complete. Current provider: $DESIGNSHIP_AI"
    echo "  Config file: .ralphex/config"
    echo ""
    echo "  To switch providers:"
    echo "    DESIGNSHIP_AI=claude ./run-opencode.sh config"
    echo "    DESIGNSHIP_AI=opencode ./run-opencode.sh config"
    echo ""
    ;;

restore)
    if [ -f ".ralphex/config.backup" ]; then
        cp ".ralphex/config.backup" ".ralphex/config"
        echo "  [config] Restored original config from .ralphex/config.backup"
    else
        echo "  [config] No backup found at .ralphex/config.backup"
        exit 1
    fi
    ;;

help|--help|-h|"")
    cat <<'HELP'

  DesignShip — OpenCode/Claude Runner
  ===================================

  Environment:
    DESIGNSHIP_AI=opencode|claude  (default: opencode)

  Commands:
    ./run-opencode.sh start       — Run the default plan (ship)
    ./run-opencode.sh ship        — Document + push + deploy plan
    ./run-opencode.sh mvp         — Original MVP build plan
    ./run-opencode.sh status      — Show completion across all plans
    ./run-opencode.sh dashboard   — Dashboard monitoring only (port 8181)
    ./run-opencode.sh config      — Setup ralphex config for selected AI
    ./run-opencode.sh restore     — Restore original ralphex config

  Examples:
    ./run-opencode.sh start
    DESIGNSHIP_AI=claude ./run-opencode.sh start
    ./run-opencode.sh status
    ./run-opencode.sh config

  Related:
    ./queue-opencode.sh           — Auto-retry wrapper with limit detection

HELP
    ;;

*)
    echo ""
    echo "  Unknown mode: $1"
    echo "  Run './run-opencode.sh help' for usage."
    exit 1
    ;;

esac
